#!/bin/bash
echo "hello linux!"
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export ROOTMNT=/root
export ROFLAG=-r
mount -n -t devtmpfs udev /dev
mount -n -t proc proc /proc
mount -n -t sysfs sysfs /sys
mount -n -t ramfs ramfs /run
udevd --daemon
udevadm trigger --action=add
udevadm settle

for x in $(cat /proc/cmdline); do
 case $x in
 root=*)
    ROOT=${x#root=}
    ;;
 ro)
   ROFLAG=-r
    ;;
 rw)
   ROFLAG=-w
   ;;
 esac
done

mount ${ROFLAG} ${ROOT} ${ROOTMNT}
udevadm control --exit
mount -n --move /dev /root/dev
mount -n --move /run /root/run
mount -n --move /proc /root/proc
mount -n --move /sys /root/sys
switch_root /root /sbin/init
# exec /bin/bash
